### ISSUE TITLE
`pulumi up` fails when upgrading from version 0.59.2 to 0.62.7

### ISSUE THREAD

**Issue by ajgassner** [pulumiverse/pulumi-exoscale#529]
panic: schemaOnlyProvider does not implement runtime operation InitLogging

using Pulumi with TypeScript

versions:
    "@pulumi/aws": "6.65.0",
    "@pulumi/kubernetes": "4.19.0",
    "@pulumi/kubernetes-cert-manager": "0.0.7",
    "@pulumi/pulumi": "3.144.1",

```
➜ pulumi up
Previewing update (default):
     Type                          Name                                                               Plan       Info
     pulumi:pulumi:Stack           pulumi-infra-default                                                          
     └─ pulumi:providers:exoscale  default_0_62_7_github_/api.github.com/pulumiverse/pulumi-exoscale             1 error

Diagnostics:
  pulumi:providers:exoscale (default_0_62_7_github_/api.github.com/pulumiverse/pulumi-exoscale):
    error: could not read plugin [/Users/xxx/.pulumi/plugins/resource-exoscale-v0.62.7/pulumi-resource-exoscale] stdout: EOF

  pulumi:pulumi:Stack (pulumi-infra-default):
    panic: schemaOnlyProvider does not implement runtime operation InitLogging
    goroutine 1 [running]:
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/pf/internal/schemashim.(*SchemaOnlyProvider).InitLogging(...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.97.0/pkg/pf/internal/schemashim/provider.go:157
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.Main({_, _}, {_, _}, {{0x104c2a540, 0x14000f51950}, {0x104041704, 0x8}, {0x0, 0x0}, ...}, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.97.0/pkg/tfbridge/main.go:71 +0x34c
    main.main()
    	/home/runner/work/pulumi-exoscale/pulumi-exoscale/provider/cmd/pulumi-resource-exoscale/main.go:31 +0xa4
```

**Comment by PStump** [comment]
I get the same error, when I try a fresh install of the latest pulumi version `3.147.0` with the latest exoscale provider `0.62.7`
(Using Python as pulumi language).

Using pulumi `1.144.1` with exoscale `0.59.2` seems to work.

**Comment by dirien** [comment]
@ajgassner can you give an example program please?

**Comment by ajgassner** [comment]
@dirien here is a minimal example
[pulumi-exo-demo.zip](https://github.com/user-attachments/files/18732012/pulumi-exo-demo.zip)

**Comment by pcuci** [comment]
Also confirming `0.59.2` works fine for creating instances in exoscale, whereas `0.62.7` borks with:

```
error: 
             Detected that /home/ubuntu/.pulumi/plugins/resource-exoscale-v0.62.7/pulumi-resource-exoscale exited prematurely.
             This is *always* a bug in the provider. Please report the issue to the provider author as appropriate.
    
    To assist with debugging we have dumped the STDOUT and STDERR streams of the plugin:
    
    panic: schemaOnlyProvider does not implement runtime operation InitLogging
    
    goroutine 1 [running]:
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/pf/internal/schemashim.(*SchemaOnlyProvider).InitLogging(...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.97.0/pkg/pf/internal/schemashim/provider.go:157
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.Main({_, _}, {_, _}, {{0x2bd0fe0, 0xc001093710}, {0x2[68](https://gitlab.com/home.cloud/serve/torrenter/-/jobs/9202913335#L68)c38e, 0x8}, {0x0, 0x0}, ...}, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.97.0/pkg/tfbridge/main.go:71 +0x390
    main.main()
    	/home/runner/work/pulumi-exoscale/pulumi-exoscale/provider/cmd/pulumi-resource-exoscale/main.go:31 +0xca
  pulumi:providers:exoscale (default_0_62_7_github_/api.github.com/pulumiverse/pulumi-exoscale):
    error: could not read plugin [/home/ubuntu/.pulumi/plugins/resource-exoscale-v0.62.7/pulumi-resource-exoscale] stdout: EOF
```

**Comment by maersu** [comment]
Same:

````
 pulumi:providers:exoscale (default_0_62_7_github_/api.github.com/pulumiverse/pulumi-exoscale):
    error: could not read plugin [/Users/maersu/.pulumi/plugins/resource-exoscale-v0.62.7/pulumi-resource-exoscale] stdout: EOF

  pulumi:pulumi:Stack (takeoff-exoscale-infra-main):
    error: 
    
             Detected that /Users/maersu/.pulumi/plugins/resource-exoscale-v0.62.7/pulumi-resource-exoscale exited prematurely.
             This is *always* a bug in the provider. Please report the issue to the provider author as appropriate.
    
    To assist with debugging we have dumped the STDOUT and STDERR streams of the plugin:
    
    panic: schemaOnlyProvider does not implement runtime operation InitLogging
    
    goroutine 1 [running]:
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/pf/internal/schemashim.(*SchemaOnlyProvider).InitLogging(...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.97.0/pkg/pf/internal/schemashim/provider.go:157
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.Main({_, _}, {_, _}, {{0x102be2540, 0x14001087440}, {0x101ff9704, 0x8}, {0x0, 0x0}, ...}, ...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.97.0/pkg/tfbridge/main.go:71 +0x34c
    main.main()
        /home/runner/work/pulumi-exoscale/pulumi-exoscale/provider/cmd/pulumi-resource-exoscale/main.go:31 +0xa4
````

**Comment by ajg-xtype** [comment]
@dirien any update on this? Is pulumi-exoscale still maintained? Thx!

**Comment by ajgassner** [comment]
Same with [v0.64.3](https://github.com/pulumiverse/pulumi-exoscale/releases/tag/v0.64.3)

**Comment by sinan-ozel** [comment]
Confirming. First time using Pulumi, very minimal program deploying a cluster failed with all versions after 0.59.2

Working code:
`__main__.py`
```
# This script defines the SKS cluster resource for Pulumi.
# To destroy the cluster, run: pulumi destroy -s <stack>
import os

import pulumi
import pulumiverse_exoscale as exoscale



CLUSTER_NAME = os.environ['CLUSTER_NAME']
REGION = os.environ.get('REGION', 'ch-gva-2')

cluster = exoscale.SksCluster("cluster",
                              zone=REGION,
                              name=CLUSTER_NAME,
                              )

pulumi.export("endpoint", cluster.endpoint)
```

`Pulumi.yaml`
```
name: sks-python-cluster
description: A minimal Python Pulumi program
runtime:
    name: python
    options:
        virtualenv: venv
```

`requirements.txt`
```
boto3==1.40.22
pulumi>=3.131.0
pulumiverse_exoscale==0.59.2
```

To replicate, change the version in Python to 0.62.7 or 0.64.3, and then see it fail. The environment I am running this on is GitHub Actions, I can post that workflow, too, if desired.

**Comment by lucj** [comment]
@ajgassner just wanted to let you know that we are working on an issue to upgrade the Pulumi provider. I'll tell you when the new release is here.

**Comment by dirien** [comment]
@ajgassner please use version `v0.66.1`, i tested it also with self-hosted state file:

```bash
➜ pulumi preview                                                        
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):  
Enter your passphrase to unlock config/secrets
Previewing update (dev):
     Type                      Name                    Plan       
 +   pulumi:pulumi:Stack       typescript-example-dev  create     
 +   └─ exoscale:index:Domain  domain                  create     

Outputs:
    domainName: "my-domain.com"
                                                                                                                                                                                                                                                                                                             
Resources:
    + 2 to create

```

@ajgassner let us know if it worked.

**Comment by dirien** [comment]
cc: @maersu @pcuci @PStump

**Comment by lucj** [comment]
Thanks for the fix, @dirien. I was able to create an SKS cluster using 0.66.1.

**Comment by ajgassner** [comment]
I can confirm! It works. Thank you all for your effort 🚀 🎉
